### ISSUE TITLE
[run error]: No such file or directory: 'gcngrasp/../data/taskgrasp/misc.pkl'

### ISSUE THREAD

**Issue by MingshanHe** [mkt1412/GraspGPT_public#4]
FileNotFoundError: [Errno 2] No such file or directory: 'gcngrasp/../data/taskgrasp/misc.pkl'

**Comment by MingshanHe** [comment]
Hi,
I have completed the instructions you have mentioned in the README and the error happened when I tried to run the Demo version command you showed in the script.

**Comment by mkt1412** [comment]
@MingshanHe Hi, thanks for the interest in our work. You may access the misc.pkl with the following link: https://gatech.box.com/s/kmffohmm7mohp7j2ol27vgx7tr6nokvz

**Comment by MingshanHe** [comment]
Thanks for your reply. I think I also need the fine named "class_list.pkl"

**Comment by mkt1412** [comment]
@MingshanHe Here you go. https://gatech.box.com/s/dmhvm3cbjiyibgc7rejh4r0d1lba753i

**Comment by 249chy** [comment]
> @MingshanHe Hi, thanks for the interest in our work. You may access the misc.pkl with the following link: https://gatech.box.com/s/kmffohmm7mohp7j2ol27vgx7tr6nokvz
This link seems to be invalid, can you share it with me again? Then, is this miss.pkl the same as the miss.pkl file in the taskgrasp dataset

**Comment by mkt1412** [comment]
@249chy Hi, this is the [updated link](https://gatech.box.com/s/t1o6u9clsdqtitlisg3qx0g1foi0v12w) to misc.pkl. This is the same as in the taskgrasp dataset. Feel free to use either one.

**Comment by 249chy** [comment]
thank you very much



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/20/2024 12:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mkt1412/GraspGPT_public] [run error]: No such file or directory: 'gcngrasp/../data/taskgrasp/misc.pkl' (Issue #4) |

@249chy Hi, this is the updated link to misc.pkl. This is the same as in the taskgrasp dataset. Feel free to use either one.

**Comment by zerofen** [comment]
This link seems to be invalid, can you share it with me again?
FileNotFoundError: [Errno 2] No such file or directory: 'gcngrasp/../data/taskgrasp/misc.pkl'
