### ISSUE TITLE
Missing Description Files

### ISSUE THREAD

**Issue by Seasandwpy** [mkt1412/GraspGPT_public#5]
Hi,
thanks for the great work, I got the following error during evaluation 'No such object description dir: gcngrasp/../data/taskgrasp/obj_gpt_v2/scrub_brush/descriptions/5', where should I download this obj_gpt_v2 folder?

**Comment by mkt1412** [comment]
Hi, sorry for the delayed response. Did you download the LA-TaskGrasp dataset under the Dataset section?

**Comment by Seasandwpy** [comment]
sorry I downloaded the taskgrasp dataset instead of the LA-TaskGrasp. After re-downloading the issue is fixed
