### ISSUE TITLE
Any schedule to release FoundationGrasp code?

### ISSUE THREAD

**Issue by HansRen1024** [mkt1412/GraspGPT_public#7]
Hi, thank you for open-sourcing the GraspGPT code for re-implementation. I noticed that you recently released a more advanced method, FoundationGrasp. It would be grateful if you could release its code as well.

**Comment by mkt1412** [comment]
Hi, thanks for your interest in our work. Although we currently do not plan to release the full implementation of FoundationGrasp, you can find a brief instruction on how to reproduce FoundationGrasp at the bottom of this repo. Hope it helps.

**Comment by HansRen1024** [comment]
> Hi, thanks for your interest in our work. Although we currently do not plan to release the full implementation of FoundationGrasp, you can find a brief instruction on how to reproduce FoundationGrasp at the bottom of this repo. Hope it helps.

Thank you so much for your prompt response!

**Comment by KomputerMaster64** [comment]
> Hi, thanks for your interest in our work. Although we currently do not plan to release the full implementation of FoundationGrasp, you can find a brief instruction on how to reproduce FoundationGrasp at the bottom of this repo. Hope it helps.

Hello
The link in the DATA section of FoundationGrasp Implementation is not working:
Step 1. Download the original LA-TaskGrasp dataset [here](https://gatech.box.com/s/ddvp9co4jv462gchp38m31kb0umkt03p) and place it in the root folder as data.

![Image](https://github.com/user-attachments/assets/cc399575-9327-4fb7-b311-34f834dd211d)

**Comment by mkt1412** [comment]
@KomputerMaster64 Hi, sorry for the delayed response. I have updated the link. You should be able to download the dataset now.
