### ISSUE TITLE
extra documentation

### ISSUE THREAD

**Issue by TontonTremblay** [mkt1412/GraspGPT_public#9]
Hello, super cool read on the paper and I really enjoy the direction you guys are heading. I appreciate the effort you guys put into making sure I can train my own version of your work, but I am more interested as an end user here. It would be cool if there was some sort of section that shows loading your trained weights, loading a point cloud, adding a prompt, and then outputting a grasp. This would help us integrate this into our robotics system. Thank you in advance. (Also I am sorry if I did not see such section if it exists -- it just did not jump at me when reading the readme).

**Comment by mkt1412** [comment]
hi @TontonTremblay ,

Thanks for your interest in our work. There is a section under Demo - Interactive version, where you can input your OpenAI key, object class, task, and pre-trained weights for inference. In this version, we pre-compute the candidate grasp poses with Contact-GraspNet (https://github.com/NVlabs/contact_graspnet). 

Let me know if further assistance is needed.
